[chore] Fix TestPerfCounter_Reset test (#36726)
#### Description

Fix the TestPerfCounter_Reset that is failing consistently. 

```terminal
=== FAIL: . TestPerfCounter_Reset (0.00s)
    watcher_test.go:131: 
        	Error Trace:	D:/a/opentelemetry-collector-contrib/opentelemetry-collector-contrib/pkg/winperfcounters/watcher_test.go:131
        	Error:      	Both arguments must be pointers
        	Test:       	TestPerfCounter_Reset
```

Root case: after upgrading `testify` circa of 2 weeks ago, since it
included:

> NotSame should fail if args are not pointers
https://github.com/stretchr/testify/issues/1661 by @sikehish in
https://github.com/stretchr/testify/pull/1664

See https://github.com/stretchr/testify/releases

#### Testing

Local test run

Co-authored-by: Antoine Toulme <atoulme@splunk.com>