[exporter/elasticsearch] validate endpoints (#33350)
**Description:**

Check that Elasticsearch `endpoints` is a list of valid URLs during
config validation. This ensures that syntactically invalid endpoints
causes a fatal error during collector startup, rather than leading to a
persistent runtime error.

Previously, setting an endpoint without a scheme would lead to an error
at runtime when attempting a bulk request to Elasticsearch:

```
...
2024-06-04T10:30:23.244+0800    error
elasticsearchexporter/elasticsearch_bulk.go:313 bulk indexer flush error
{"kind": "exporter", "data_type": "traces", "name": "elasticsearch",
"error": "failed to execute the request: unsupported protocol scheme
\"\""}
...
```

Now the collector fails to start up:

```
$ make run
cd ./cmd/otelcontribcol && GO111MODULE=on go run --race . --config ../../local/config.yaml 
Error: invalid configuration: exporters::elasticsearch: invalid endpoint "localhost": invalid scheme "", expected "http" or "https"
2024/06/04 12:23:50 collector server run finished with error: invalid configuration: exporters::elasticsearch: invalid endpoint "localhost": invalid scheme "", expected "http" or "https"
exit status 1
make: *** [Makefile:255: run] Error 1
```

**Link to tracking Issue:**

N/A

**Testing:** <Describe what testing was performed and which tests were
added.>

**Documentation:**

N/A