Apply the right Validate() func to emfexporter and k8sobserver so config.Validate from core can get compiled (#3020)
As we're adding `validatable` interface to `config.processor | extension | exporter` in core package. `Contrib` package is failed to be built due to the following errors. This PR is to fix the ambiguous Config.Validate errors.

```
exporter/awsemfexporter/factory.go:40:9: cannot use &Config literal (type *Config) as type config.Exporter in return argument:
	*Config does not implement config.Exporter (wrong type for Validate method)
		have Validate()
		want Validate() error

extension/observer/k8sobserver/factory.go:64:15: Config.Validate is ambiguous

```

**Link to tracking Issue:** 
https://github.com/open-telemetry/opentelemetry-collector/pull/2898